### ISSUE TITLE
Filtering for assets

### ISSUE THREAD

**Issue by phoebus-84** [dyne/zenflows#15]
We need filter for query assets (proposal) by 
- primaryIntents.resourceInventoriedAs.conformTo: [ID!] 
- primaryIntents.resourceInventoriedAs.primaryAccountable: [ID!]. 
it would be great have a filter also for:
primaryIntents.resourceInventoriedAs.currentLocation.lat and long
where lat and long should be in a range or something similar to check proximity with the query values

we need also filter for the agents query, where we can check if a string is included in the name field or username field

**Comment by srfsh** [comment]
Except for `primaryIntents.resourceInventoriedAs.currentLocation`, they are implemented.
