### ISSUE TITLE
Error on gql bad format

### ISSUE THREAD

**Issue by puria** [dyne/zenflows#23]
When a gql query starts with a '\n' the or some white space the signature does not match.
Hopw should we handle queries? trim from both parties? or leave everytime in verbatim?

<3

**Comment by srfsh** [comment]
Recently, we were able to deal with this by properly signing the generated JSON body of GraphQL clients (thanks to @albertolerda).  This should fix this.  Tell me if it doesn't.

**Comment by srfsh** [comment]
I'm closing this in favor of @albertolerda's fix.
