### ISSUE TITLE
Allow tags inside assets

### ISSUE THREAD

**Issue by puria** [dyne/zenflows#7]
Create a mutation to allow to create tags related to assets

**Comment by srfsh** [comment]
Is this related to saving of tags in the db?  Because we already can do that, but in a way that I need to benchmark its performance (fine for now, since it still allows for filtering).

Please close this if you think it is resolved, else tell me exactly what we need to implement.   ^^

**Comment by puria** [comment]
Yes thanks 😚!

We do actually save in the `createEconomicEvent` mutation some field like `resourceClassifiedAs` (what we call tags).

What I want to achieve is to retrieve a list of the `proposals` that are filtered/grouped by the `resourceClassifiedAs` (tags) given at creation time.

Do we miss something, to be able to do that?

**Comment by srfsh** [comment]
Implemented in 4ff13842464691001fbe98354b23828108efabc7.
